[package]
name = "xim"
version = "0.4.0"
authors = ["Damian Poddebniak <poddebniak@fh-muenster.de>"]

[dependencies]
chan         = "*"
chan-signal  = "*"
clippy       = {version = "*", optional = true}
docopt       = "*"
serde        = "*"
serde_derive = "*"
termion      = "*"

[dev-dependencies]
quickcheck   = "*"

[features]
default = []
